In [2]:
import numpy as np
print(np.__version__)
np.__config__.show()
# Print the numpy version 1 & 2

1.10.4
lapack_opt_info:
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/YL/anaconda/include']
    library_dirs = ['/Users/YL/anaconda/lib']
    libraries = ['mkl_lapack95_lp64', 'mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
blas_opt_info:
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/YL/anaconda/include']
    library_dirs = ['/Users/YL/anaconda/lib']
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
blas_mkl_info:
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/YL/anaconda/include']
    library_dirs = ['/Users/YL/anaconda/lib']
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
openblas_lapack_info:
  NOT AVAILABLE
lapack_mkl_info:
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/YL/anaconda/include']
    lib

In [3]:
# Create a null vector of size 10
Z = np.zeros(10)
print(Z)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [6]:
python -c "numpy.info(numpy.add)"

SyntaxError: invalid syntax (<ipython-input-6-fc9e40481200>, line 1)

In [7]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [8]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [11]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [58]:
print(np.nonzero([1,2,0,0,4,0]))
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)
(array([0, 1, 4]),)


In [13]:
Z = np.eye(3)
print(Z)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [14]:
Z = np.random.random((3,3,3))
print(Z)

[[[ 0.2431224   0.8967156   0.68246852]
  [ 0.03340732  0.10763619  0.28540315]
  [ 0.03546862  0.15845448  0.69180475]]

 [[ 0.61621687  0.60839623  0.40446773]
  [ 0.1898507   0.17073547  0.33753578]
  [ 0.11046852  0.61888985  0.11572353]]

 [[ 0.9295336   0.63810481  0.36772141]
  [ 0.96065103  0.97454335  0.87635746]
  [ 0.99380109  0.87979903  0.08635256]]]


In [18]:
Z = np.random.random((10,10))
print(Z)
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)


[[ 0.46308259  0.7206973   0.89353537  0.80980711  0.24422259  0.68738271
   0.81138415  0.95951445  0.62544948  0.50486388]
 [ 0.99067827  0.75716321  0.95788425  0.00577105  0.10956454  0.92001811
   0.39949603  0.44366544  0.57147931  0.88490534]
 [ 0.88003065  0.58480711  0.98162196  0.05421864  0.14661588  0.08168542
   0.15853712  0.06975509  0.75341491  0.50636087]
 [ 0.53641323  0.7511381   0.25011012  0.99039642  0.27473716  0.8142561
   0.95897529  0.32309501  0.55283032  0.89915788]
 [ 0.83685902  0.85687887  0.2497599   0.70888622  0.63686537  0.97246479
   0.47337572  0.62802822  0.18204363  0.96872743]
 [ 0.39810548  0.35173716  0.94948297  0.91735263  0.55418292  0.85544138
   0.90188914  0.04043436  0.3766512   0.67836592]
 [ 0.81489282  0.89433247  0.70875779  0.44491722  0.08227674  0.24468987
   0.28328673  0.03292887  0.13244116  0.47159955]
 [ 0.27718655  0.53959974  0.859644    0.70973549  0.26663999  0.22680138
   0.10042754  0.2419568   0.82521045  0.76440004]
 

In [17]:
Z = np.random.random(30)
print(Z)
m = Z.mean()
print(m)

[ 0.49859362  0.52819731  0.50886159  0.18907345  0.18626206  0.96579996
  0.71084651  0.54997763  0.57746723  0.18169162  0.45035181  0.19576641
  0.12154407  0.27725889  0.58754629  0.90382263  0.82825796  0.65567625
  0.53456331  0.00964547  0.59219675  0.26054909  0.6228521   0.98436175
  0.5543003   0.79439691  0.54983323  0.59576268  0.02063836  0.46380273]
0.496663264322


In [20]:
Z = np.ones((10,10))
print(Z)
Z[1:-1,1:-1] = 0
print(Z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [21]:
# Exercise 15 a 
0 * np.nan

nan

In [22]:
# Exercise 15 b
np.nan == np.nan

False

In [23]:
# Exercise 15 c
np.inf > np.nan

False

In [24]:
# Exercise 15 d
np.inf - np.nan

nan

In [25]:
# Exercise 15 e
0.3 == 3 * 0.1

False

In [26]:
# Exercise 16
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [27]:
# Exercise 17
Z = np.zeros((8,8),dtype=int)
print(Z)
Z[1::2,::2] = 1
print(Z)
Z[::2,1::2] = 1
print(Z)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [28]:
# Exercise 18
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [29]:
# Exercise 19
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [30]:
# Exercise 20
Z = np.random.random((5,5))
print(Z)
Zmax, Zmin = Z.max(), Z.min()
print(Zmax, Zmin)
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[ 0.48159761  0.36822403  0.4271869   0.84461933  0.78650871]
 [ 0.59453003  0.37364282  0.90106967  0.6575647   0.05271929]
 [ 0.52567018  0.62982678  0.99791939  0.68708492  0.51837384]
 [ 0.3521251   0.83755854  0.44462396  0.50957282  0.38322857]
 [ 0.83590708  0.31073049  0.85311002  0.92311836  0.620608  ]]
0.997919394064 0.0527192881897
[[ 0.45374341  0.33379677  0.39617814  0.83781206  0.77633236]
 [ 0.57322331  0.33952973  0.89753522  0.63991255  0.        ]
 [ 0.50037118  0.61056647  1.          0.67114427  0.49265181]
 [ 0.31676447  0.8303419   0.41462614  0.48334054  0.34967122]
 [ 0.82859469  0.27296992  0.84679501  0.92086222  0.60081322]]


In [33]:
# Exercise 21
print(np.ones((5,3)))
print(np.ones((3,2)))
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


In [35]:
# Exercise 22
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


In [36]:
# Exercise 23
def generate():
    for x in xrange(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

NameError: name 'xrange' is not defined

In [37]:
# Exercise 24
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


In [38]:
# Exercise 25
Z = np.random.random(10)
Z.sort()
print(Z)

[ 0.0176269   0.13054134  0.30382389  0.4328926   0.48226272  0.66946737
  0.78713788  0.87964954  0.88995943  0.94494291]


In [39]:
# Exercise 26
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


In [42]:
# Exercise 27
Z = np.zeros(10)
print(Z)
Z.flags.writeable = False
Z[0] = 1

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


ValueError: assignment destination is read-only

In [44]:
# Exercise 28
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[ 1.03814628  0.96414528  0.40586839  0.7450447   1.3815051   0.32871909
  1.08209655  0.83874249  0.90317306  0.97568768]
[ 1.11748604  0.39780737  0.92743185  1.43272972  0.78155821  1.43293202
  0.94264837  0.08787154  0.23514645  0.81000595]


In [45]:
# Exercise 29
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[ 0.8354801   0.81167193  0.85533893  0.90559938  0.46458225  0.
  0.82745285  0.30929151  0.37081288  0.87404356]


In [46]:
# Exercise 30
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(Z)

[[(0.0, 0.0) (0.1111111111111111, 0.0) (0.2222222222222222, 0.0)
  (0.3333333333333333, 0.0) (0.4444444444444444, 0.0)
  (0.5555555555555556, 0.0) (0.6666666666666666, 0.0)
  (0.7777777777777777, 0.0) (0.8888888888888888, 0.0) (1.0, 0.0)]
 [(0.0, 0.1111111111111111) (0.1111111111111111, 0.1111111111111111)
  (0.2222222222222222, 0.1111111111111111)
  (0.3333333333333333, 0.1111111111111111)
  (0.4444444444444444, 0.1111111111111111)
  (0.5555555555555556, 0.1111111111111111)
  (0.6666666666666666, 0.1111111111111111)
  (0.7777777777777777, 0.1111111111111111)
  (0.8888888888888888, 0.1111111111111111) (1.0, 0.1111111111111111)]
 [(0.0, 0.2222222222222222) (0.1111111111111111, 0.2222222222222222)
  (0.2222222222222222, 0.2222222222222222)
  (0.3333333333333333, 0.2222222222222222)
  (0.4444444444444444, 0.2222222222222222)
  (0.5555555555555556, 0.2222222222222222)
  (0.6666666666666666, 0.2222222222222222)
  (0.7777777777777777, 0.2222222222222222)
  (0.8888888888888888, 0.222222222222

In [47]:
# Exercise 31
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.40282e+38
3.40282e+38
1.19209e-07
-1.79769313486e+308
1.79769313486e+308
2.22044604925e-16


In [48]:
# Exercise 32
np.set_printoptions(threshold=np.nan)
Z = np.zeros((25,25))
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  

In [49]:
# Exercise 33
np.set_printoptions(threshold=np.nan)
Z = np.zeros((25,25))
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  

In [50]:
# Exercise 34
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

46


In [51]:
# Exercise 35
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(Z)


[((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))]


In [52]:
# Exercise 36
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[ 0.          0.8771947   0.75504174  0.23930504  1.00245216  0.59430705
   0.4468696   0.66434278  0.37692437  0.83426948]
 [ 0.8771947   0.          0.59670673  0.6674007   0.86470472  0.66354853
   0.76207781  0.9538797   0.51462165  0.48364116]
 [ 0.75504174  0.59670673  0.          0.53138921  0.3091036   0.18068156
   0.35901774  0.4121549   0.61518295  0.15171766]
 [ 0.23930504  0.6674007   0.53138921  0.          0.80299107  0.38910364
   0.28807063  0.54361736  0.23421271  0.59819797]
 [ 1.00245216  0.86470472  0.3091036   0.80299107  0.          0.41402535
   0.56000926  0.44803634  0.91848504  0.38144103]
 [ 0.59430705  0.66354853  0.18068156  0.38910364  0.41402535  0.
   0.17838323  0.290369    0.52841634  0.31304246]
 [ 0.4468696   0.76207781  0.35901774  0.28807063  0.56000926  0.17838323
   0.          0.2584942   0.489516    0.48466607]
 [ 0.66434278  0.9538797   0.4121549   0.54361736  0.44803634  0.290369
   0.2584942   0.          0.74696045  0.56380616]
 [ 0.37692

In [53]:
# Exercise 37
Z = np.arange(10, dtype=np.int32)
print(Z)
Z = Z.astype(np.float32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [54]:
# Exercise 38
1,2,3,4,5
6,,,7,8
,,9,10,11

SyntaxError: invalid syntax (<ipython-input-54-5398b2ea30f8>, line 3)

In [55]:
Z = np.genfromtxt("missing.dat", delimiter=",")

OSError: missing.dat not found.

In [56]:
# Exercise 39
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [57]:
# Exercise 40
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[ 0.36787944  0.44822088  0.51979489  0.57375342  0.60279818  0.60279818
   0.57375342  0.51979489  0.44822088  0.36787944]
 [ 0.44822088  0.54610814  0.63331324  0.69905581  0.73444367  0.73444367
   0.69905581  0.63331324  0.54610814  0.44822088]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [

In [61]:
# Exercise 41
n = 10
p = 3
Z = np.zeros((n,n))
print(Z)
print(np.put(Z, np.random.choice(range(n*n), p, replace=False),1))

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
None


In [63]:
# Exercise 42
X = np.random.rand(5, 10)
print(X)
# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
print(Y)
# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[ 0.62160168  0.6686885   0.0066853   0.36649774  0.30046683  0.77491565
   0.82091045  0.27953947  0.01053769  0.50982167]
 [ 0.92994191  0.85481511  0.49003799  0.26920243  0.8883886   0.16527392
   0.3225977   0.27312537  0.14599211  0.76827142]
 [ 0.90386636  0.0509822   0.39363288  0.84054279  0.97393995  0.10082385
   0.95211226  0.31375465  0.94786096  0.03666785]
 [ 0.56069091  0.07022465  0.20627249  0.91418854  0.37235955  0.85695968
   0.31189756  0.76074502  0.57354996  0.0112149 ]
 [ 0.63289051  0.2573218   0.9752195   0.82724304  0.2300466   0.67049983
   0.93209669  0.68358966  0.56892049  0.51773299]]
[[ 0.18563519  0.232722   -0.4292812  -0.06946876 -0.13549967  0.33894915
   0.38494396 -0.15642703 -0.42542881  0.07385517]
 [ 0.41917725  0.34405046 -0.02072667 -0.24156222  0.37762394 -0.34549074
  -0.18816696 -0.23763929 -0.36477254  0.25750676]
 [ 0.35244799 -0.50043618 -0.1577855   0.28912441  0.42252158 -0.45059453
   0.40069389 -0.23766373  0.39644259 -0.51475053]

In [64]:
# Exercise 43
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[8 5 5]
 [9 5 2]
 [5 6 6]]
[[8 5 5]
 [9 5 2]
 [5 6 6]]


In [65]:
# Exercise 44
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [66]:
# Exercise 45
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.507321234877


In [67]:
# Exercise 46
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[ 2.  1.  7.  1.  2.  2.  2.  6.  4.  3.]


In [68]:
# Exercise 47
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[ 0.  7.  0.  6.  5.  0.  0.  0.  0.  3.]


In [69]:
# Exercise 48
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


In [70]:
# Exercise 49
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[49 56 72 25]
 [75 58 69 47]
 [63 71 55 50]]


In [71]:
# Exercise 50
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[ 0.49899526  0.43943328  0.45359564  0.35909836  0.49919128  0.38445487
  0.26475434  0.53503531  0.65579046  0.27849739]


In [73]:
# Exercise 51
# Slow version
np.diag(np.dot(A, B))
# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B).

SyntaxError: invalid syntax (<ipython-input-73-00387287b2d4>, line 8)

In [74]:
# Exercise 52
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


In [75]:
# Exercise 53
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]]


In [76]:
# Exercise 54
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [77]:
# Exercise 55
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[(2, 49) (5, 41) (5, 70) (10, 56) (10, 95) (23, 54) (23, 74) (26, 35)
 (26, 91) (30, 33) (30, 70) (30, 87) (30, 93) (33, 87) (35, 91) (36, 60)
 (36, 67) (41, 70) (42, 83) (42, 98) (49, 49) (50, 70) (50, 96) (54, 74)
 (56, 95) (60, 67) (70, 93) (70, 96) (83, 98)]


In [78]:
# Exercise 56
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [79]:
# Exercise 57
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))


[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.
  16.  17.  18.]


In [80]:
# Exercise 58
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [81]:
# Exercise 59
Z = np.random.randint(0,2,100)
np.logical_not(arr, out=arr)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(arr, out=arr)

NameError: name 'arr' is not defined

In [82]:
# Exercise 60
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[  0.86999975   3.57523727   8.24603011   6.55065794   3.61065293
   5.25498013   0.35294519   3.34556077   3.17405072  11.95306695]
